const commandInfos = {
    "id": 1,
    "name": "初始化服务",
    "type": null,
    "commandState": "ERROR",
    "submitTime": "2023-02-14T06:09:21.760+00:00",
    "startTime": "2023-02-14T06:09:23.539+00:00",
    "endTime": "2023-02-14T06:10:09.751+00:00",
    "currentProgress": 36,
    "operateUserId": 1000,
    "clusterId": 1,
    "tasksMap": {
        "ZOOKEEPER1": [
            {
                "id": 1,
                "taskShowSortNum": 1,
                "taskName": "ZOOKEEPER_SERVER :拉取docker registry镜像到节点 (node001)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":1,\"hostName\":\"node001\",\"ip\":\"10.11.0.1\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :拉取docker registry镜像到节点 (node001)\"}",
                "processorClassName": "com.data.udh.processor.ExampleTask",
                "commandState": "SUCCESS",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-1",
                "startTime": "2023-02-14T06:09:23.631+00:00",
                "endTime": "2023-02-14T06:09:28.673+00:00",
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 100,
                "powerjobInstanceId": null
            },
            {
                "id": 2,
                "taskShowSortNum": 2,
                "taskName": "ZOOKEEPER_SERVER :拉取docker registry镜像到节点 (node002)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":2,\"hostName\":\"node002\",\"ip\":\"10.11.0.2\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :拉取docker registry镜像到节点 (node002)\"}",
                "processorClassName": "com.data.udh.processor.ExampleTask",
                "commandState": "SUCCESS",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-2",
                "startTime": "2023-02-14T06:09:28.758+00:00",
                "endTime": "2023-02-14T06:09:33.793+00:00",
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 50,
                "powerjobInstanceId": null
            },
            {
                "id": 3,
                "taskShowSortNum": 3,
                "taskName": "ZOOKEEPER_SERVER :拉取docker registry镜像到节点 (node003)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":3,\"hostName\":\"node003\",\"ip\":\"10.11.0.3\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :拉取docker registry镜像到节点 (node003)\"}",
                "processorClassName": "com.data.udh.processor.ExampleTask",
                "commandState": "SUCCESS",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-3",
                "startTime": "2023-02-14T06:09:33.878+00:00",
                "endTime": "2023-02-14T06:09:38.931+00:00",
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 30,
                "powerjobInstanceId": null
            },
            {
                "id": 4,
                "taskShowSortNum": 4,
                "taskName": "ZOOKEEPER_SERVER :拉取docker registry镜像到节点 (node004)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":4,\"hostName\":\"node004\",\"ip\":\"10.11.0.4\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :拉取docker registry镜像到节点 (node004)\"}",
                "processorClassName": "com.data.udh.processor.ExampleTask",
                "commandState": "RUNNING",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-4",
                "startTime": "2023-02-14T06:09:39.011+00:00",
                "endTime": "2023-02-14T06:09:44.041+00:00",
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 10,
                "powerjobInstanceId": null
            },
            {
                "id": 5,
                "taskShowSortNum": 5,
                "taskName": "ZOOKEEPER_SERVER :拉取docker registry镜像到节点 (node005)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":5,\"hostName\":\"node005\",\"ip\":\"10.11.0.5\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :拉取docker registry镜像到节点 (node005)\"}",
                "processorClassName": "com.data.udh.processor.ExampleTask",
                "commandState": "ERROR",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-5",
                "startTime": "2023-02-14T06:09:44.109+00:00",
                "endTime": "2023-02-14T06:09:49.146+00:00",
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 20,
                "powerjobInstanceId": null
            },
            {
                "id": 6,
                "taskShowSortNum": 6,
                "taskName": "ZOOKEEPER_SERVER :拉取docker registry镜像到节点 (node006)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":6,\"hostName\":\"node006\",\"ip\":\"10.11.0.6\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :拉取docker registry镜像到节点 (node006)\"}",
                "processorClassName": "com.data.udh.processor.ExampleTask",
                "commandState": "SUCCESS",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-6",
                "startTime": "2023-02-14T06:09:49.215+00:00",
                "endTime": "2023-02-14T06:09:54.250+00:00",
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 0,
                "powerjobInstanceId": null
            },
            {
                "id": 7,
                "taskShowSortNum": 7,
                "taskName": "ZOOKEEPER_SERVER :安装服务角色到节点 (node001)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":7,\"hostName\":\"node001\",\"ip\":\"10.11.0.1\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :安装服务角色到节点 (node001)\"}",
                "processorClassName": "com.data.udh.processor.ExampleTask",
                "commandState": "SUCCESS",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-7",
                "startTime": "2023-02-14T06:09:54.317+00:00",
                "endTime": "2023-02-14T06:09:59.351+00:00",
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 0,
                "powerjobInstanceId": null
            },
            {
                "id": 8,
                "taskShowSortNum": 8,
                "taskName": "ZOOKEEPER_SERVER :安装服务角色到节点 (node002)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":8,\"hostName\":\"node002\",\"ip\":\"10.11.0.2\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :安装服务角色到节点 (node002)\"}",
                "processorClassName": "com.data.udh.processor.ExampleTask",
                "commandState": "SUCCESS",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-8",
                "startTime": "2023-02-14T06:09:59.414+00:00",
                "endTime": "2023-02-14T06:10:04.449+00:00",
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 0,
                "powerjobInstanceId": null
            },
            {
                "id": 9,
                "taskShowSortNum": 9,
                "taskName": "ZOOKEEPER_SERVER :安装服务角色到节点 (node003)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":9,\"hostName\":\"node003\",\"ip\":\"10.11.0.3\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :安装服务角色到节点 (node003)\"}",
                "processorClassName": "com.data.udh.processor.ExampleTask",
                "commandState": "SUCCESS",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-9",
                "startTime": "2023-02-14T06:10:04.525+00:00",
                "endTime": "2023-02-14T06:10:09.567+00:00",
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 0,
                "powerjobInstanceId": null
            },
            {
                "id": 10,
                "taskShowSortNum": 10,
                "taskName": "ZOOKEEPER_SERVER :安装服务角色到节点 (node004)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":10,\"hostName\":\"node004\",\"ip\":\"10.11.0.4\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :安装服务角色到节点 (node004)\"}",
                "processorClassName": "com.data.udh.processor.ExampleTask",
                "commandState": "ERROR",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-10",
                "startTime": "2023-02-14T06:10:09.647+00:00",
                "endTime": "2023-02-14T06:10:09.685+00:00",
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 0,
                "powerjobInstanceId": null
            },
            {
                "id": 11,
                "taskShowSortNum": 11,
                "taskName": "ZOOKEEPER_SERVER :安装服务角色到节点 (node005)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":11,\"hostName\":\"node005\",\"ip\":\"10.11.0.5\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :安装服务角色到节点 (node005)\"}",
                "processorClassName": "com.data.udh.processor.ExampleTask",
                "commandState": "WAITING",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-11",
                "startTime": null,
                "endTime": null,
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 0,
                "powerjobInstanceId": null
            },
            {
                "id": 12,
                "taskShowSortNum": 12,
                "taskName": "ZOOKEEPER_SERVER :安装服务角色到节点 (node006)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":12,\"hostName\":\"node006\",\"ip\":\"10.11.0.6\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :安装服务角色到节点 (node006)\"}",
                "processorClassName": "com.data.udh.processor.ExampleTask",
                "commandState": "WAITING",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-12",
                "startTime": null,
                "endTime": null,
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 0,
                "powerjobInstanceId": null
            },
            {
                "id": 13,
                "taskShowSortNum": 13,
                "taskName": "ZOOKEEPER_SERVER :配置服务角色到节点 (node001)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":13,\"hostName\":\"node001\",\"ip\":\"10.11.0.1\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :配置服务角色到节点 (node001)\"}",
                "processorClassName": "com.data.udh.processor.ConfigTask",
                "commandState": "WAITING",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-13",
                "startTime": null,
                "endTime": null,
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 0,
                "powerjobInstanceId": null
            },
            {
                "id": 14,
                "taskShowSortNum": 14,
                "taskName": "ZOOKEEPER_SERVER :配置服务角色到节点 (node002)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":14,\"hostName\":\"node002\",\"ip\":\"10.11.0.2\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :配置服务角色到节点 (node002)\"}",
                "processorClassName": "com.data.udh.processor.ConfigTask",
                "commandState": "WAITING",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-14",
                "startTime": null,
                "endTime": null,
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 0,
                "powerjobInstanceId": null
            },
            {
                "id": 15,
                "taskShowSortNum": 15,
                "taskName": "ZOOKEEPER_SERVER :配置服务角色到节点 (node003)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":15,\"hostName\":\"node003\",\"ip\":\"10.11.0.3\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :配置服务角色到节点 (node003)\"}",
                "processorClassName": "com.data.udh.processor.ConfigTask",
                "commandState": "WAITING",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-15",
                "startTime": null,
                "endTime": null,
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 0,
                "powerjobInstanceId": null
            },
            {
                "id": 16,
                "taskShowSortNum": 16,
                "taskName": "ZOOKEEPER_SERVER :配置服务角色到节点 (node004)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":16,\"hostName\":\"node004\",\"ip\":\"10.11.0.4\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :配置服务角色到节点 (node004)\"}",
                "processorClassName": "com.data.udh.processor.ConfigTask",
                "commandState": "WAITING",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-16",
                "startTime": null,
                "endTime": null,
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 0,
                "powerjobInstanceId": null
            },
            {
                "id": 17,
                "taskShowSortNum": 17,
                "taskName": "ZOOKEEPER_SERVER :配置服务角色到节点 (node005)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":17,\"hostName\":\"node005\",\"ip\":\"10.11.0.5\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :配置服务角色到节点 (node005)\"}",
                "processorClassName": "com.data.udh.processor.ConfigTask",
                "commandState": "WAITING",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-17",
                "startTime": null,
                "endTime": null,
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 0,
                "powerjobInstanceId": null
            },
            {
                "id": 18,
                "taskShowSortNum": 18,
                "taskName": "ZOOKEEPER_SERVER :配置服务角色到节点 (node006)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":18,\"hostName\":\"node006\",\"ip\":\"10.11.0.6\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :配置服务角色到节点 (node006)\"}",
                "processorClassName": "com.data.udh.processor.ConfigTask",
                "commandState": "WAITING",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-18",
                "startTime": null,
                "endTime": null,
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 0,
                "powerjobInstanceId": null
            },
            {
                "id": 19,
                "taskShowSortNum": 19,
                "taskName": "ZOOKEEPER_SERVER :添加k8s节点标签 (node001)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":19,\"hostName\":\"node001\",\"ip\":\"10.11.0.1\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :添加k8s节点标签 (node001)\"}",
                "processorClassName": "com.data.udh.processor.ExampleTask",
                "commandState": "WAITING",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-19",
                "startTime": null,
                "endTime": null,
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 0,
                "powerjobInstanceId": null
            },
            {
                "id": 20,
                "taskShowSortNum": 20,
                "taskName": "ZOOKEEPER_SERVER :添加k8s节点标签 (node002)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":20,\"hostName\":\"node002\",\"ip\":\"10.11.0.2\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :添加k8s节点标签 (node002)\"}",
                "processorClassName": "com.data.udh.processor.ExampleTask",
                "commandState": "WAITING",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-20",
                "startTime": null,
                "endTime": null,
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 0,
                "powerjobInstanceId": null
            },
            {
                "id": 21,
                "taskShowSortNum": 21,
                "taskName": "ZOOKEEPER_SERVER :添加k8s节点标签 (node003)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":21,\"hostName\":\"node003\",\"ip\":\"10.11.0.3\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :添加k8s节点标签 (node003)\"}",
                "processorClassName": "com.data.udh.processor.ExampleTask",
                "commandState": "WAITING",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-21",
                "startTime": null,
                "endTime": null,
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 0,
                "powerjobInstanceId": null
            },
            {
                "id": 22,
                "taskShowSortNum": 22,
                "taskName": "ZOOKEEPER_SERVER :添加k8s节点标签 (node004)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":22,\"hostName\":\"node004\",\"ip\":\"10.11.0.4\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :添加k8s节点标签 (node004)\"}",
                "processorClassName": "com.data.udh.processor.ExampleTask",
                "commandState": "WAITING",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-22",
                "startTime": null,
                "endTime": null,
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 0,
                "powerjobInstanceId": null
            },
            {
                "id": 23,
                "taskShowSortNum": 23,
                "taskName": "ZOOKEEPER_SERVER :添加k8s节点标签 (node005)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":23,\"hostName\":\"node005\",\"ip\":\"10.11.0.5\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :添加k8s节点标签 (node005)\"}",
                "processorClassName": "com.data.udh.processor.ExampleTask",
                "commandState": "WAITING",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-23",
                "startTime": null,
                "endTime": null,
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 0,
                "powerjobInstanceId": null
            },
            {
                "id": 24,
                "taskShowSortNum": 24,
                "taskName": "ZOOKEEPER_SERVER :添加k8s节点标签 (node006)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":24,\"hostName\":\"node006\",\"ip\":\"10.11.0.6\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :添加k8s节点标签 (node006)\"}",
                "processorClassName": "com.data.udh.processor.ExampleTask",
                "commandState": "WAITING",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-24",
                "startTime": null,
                "endTime": null,
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 0,
                "powerjobInstanceId": null
            },
            {
                "id": 25,
                "taskShowSortNum": 25,
                "taskName": "ZOOKEEPER_SERVER :启动k8s服务",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":25,\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :启动k8s服务\"}",
                "processorClassName": "com.data.udh.processor.ExampleTask",
                "commandState": "WAITING",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-25",
                "startTime": null,
                "endTime": null,
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 0,
                "powerjobInstanceId": null
            }
        ],
        "ZOOKEEPER2": [
            {
                "id": 1,
                "taskShowSortNum": 1,
                "taskName": "ZOOKEEPER_SERVER :拉取docker registry镜像到节点 (node001)",
                "taskParam": "{\"commandId\":1,\"commandTaskId\":1,\"hostName\":\"node001\",\"ip\":\"10.11.0.1\",\"roleName\":\"ZOOKEEPER_SERVER\",\"serviceInstanceId\":1,\"stackServiceId\":2,\"taskName\":\"ZOOKEEPER_SERVER :拉取docker registry镜像到节点 (node001)\"}",
                "processorClassName": "com.data.udh.processor.ExampleTask",
                "commandState": "SUCCESS",
                "taskLogPath": "/Volumes/Samsung_T5/opensource/e-mapreduce/log/1-1",
                "startTime": "2023-02-14T06:09:23.631+00:00",
                "endTime": "2023-02-14T06:09:28.673+00:00",
                "commandTaskGroupId": null,
                "commandId": 1,
                "serviceInstanceId": 1,
                "serviceInstanceName": "ZOOKEEPER1",
                "progress": 10,
                "powerjobInstanceId": null
            },
        ]
    }
}
const statusColor = {
    'ERROR': '#f5222d',
    'RUNNING': '#1890ff',
    'SUCCESS': '#52c41a',
    'DEFAULT': '#f5222d',
  }

const trailColor = {
    'ERROR': '#fbced1',
    'RUNNING': '#9dcefb',
    'SUCCESS': '#cbfab4',
    'DEFAULT': '#f5222d',
}

export {
    commandInfos,
    statusColor,
    trailColor
} 