FROM registry.cn-guangzhou.aliyuncs.com/bigdata200/seatunnel:2.3.7

ENV SEATUNNEL_WEB_VERSION="1.0.1"
ENV SEATUNNEL_WEB_HOME="/opt/seatunnel-web"
ENV PATH=$PATH:$SEATUNNEL_WEB_HOME/bin

WORKDIR /opt
RUN wget https://dlcdn.apache.org/seatunnel/seatunnel-web/${SEATUNNEL_WEB_VERSION}/apache-seatunnel-web-${SEATUNNEL_WEB_VERSION}-bin.tar.gz
RUN tar -xzvf apache-seatunnel-web-${SEATUNNEL_WEB_VERSION}-bin.tar.gz && rm -f *.gz
RUN mv apache-seatunnel-web-* ${SEATUNNEL_WEB_HOME}
RUN apt-get install -y mysql-client
WORKDIR $SEATUNNEL_WEB_HOME

ENV MYSQL_JDBC_DRIVER_VERSION=8.0.30
RUN wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/${MYSQL_JDBC_DRIVER_VERSION}/mysql-connector-java-${MYSQL_JDBC_DRIVER_VERSION}.jar \
    && mv mysql-connector-java-${MYSQL_JDBC_DRIVER_VERSION}.jar $SEATUNNEL_WEB_HOME/libs/

RUN apt -y install maven &&  mvn -N io.takari:maven:wrapper
RUN bash bin/download_datasource.sh 1.0.1




