{
 "title": "Flink Dashboard",
 "description": "Flink dashboard :\n\nmetrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter\nmetrics.reporter.prom.port: 9251\nmetrics.system-resource: true\nmetrics.system-resource-probing-interval: 5000\nmetrics.latency.interval: 5000\nstate.backend.rocksdb.metrics.actual-delayed-write-rate: true\nstate.backend.rocksdb.metrics.background-errors: true\nstate.backend.rocksdb.metrics.num-deletes-imm-mem-tables: true\nstate.backend.rocksdb.metrics.num-entries-imm-mem-tables: true\nstate.backend.rocksdb.metrics.num-snapshots: true",
 "tags": [ "flink" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "job_name", "label": "job_name", "query": { "query": "label_values(job_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Slots",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "# of TaskManagers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers{job=\"jobmanager\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Taskslots available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsAvailable{job=\"jobmanager\"}"
    }
   ]
  },
  {
   "title": "# of Running Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRunningJobs{job=\"jobmanager\"}",
     "legendFormat": "{{instance}} jobmanager运行的job数量"
    }
   ]
  },
  {
   "title": "Taskslots total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal{job=\"jobmanager\"}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TaskManager Garbage Collection count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(flink_jobmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Count[1m])",
     "legendFormat": "{{tm_id}} 老年代gc count"
    },
    {
     "expr": "delta(flink_jobmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Count[1m])",
     "legendFormat": "{{tm_id}} 年轻代gc count"
    }
   ]
  },
  {
   "title": "TaskManagers Garbage Collection Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time[1m])",
     "legendFormat": "{{tm_id}}年轻代gc时间"
    },
    {
     "expr": "delta(flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time[1m])",
     "legendFormat": "{{tm_id}}老年代gc时间"
    }
   ]
  },
  {
   "title": "live Thread count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Threads_Count",
     "legendFormat": "{{instance}} jobManager live Thread counts"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Threads_Count",
     "legendFormat": "{{instance}} taskManger live Thread counts"
    }
   ]
  },
  {
   "title": "CheckPoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "lastCheckpointDuration",
   "type": "graph",
   "description": "lastCheckpointDuration",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointDuration{job_name=~\"$job_name\"}",
     "legendFormat": "{{instance}}{{job_name}}"
    }
   ]
  },
  {
   "title": "Last CheckPoint Size",
   "type": "graph",
   "description": "Last CheckPoint Size",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointSize{job_name=~\"$job_name\"}",
     "legendFormat": "{{instance}}_{{job_name}}"
    }
   ]
  },
  {
   "title": "numberOfFailedCheckpoints",
   "type": "graph",
   "description": "numberOfFailedCheckpoints",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(flink_jobmanager_job_numberOfFailedCheckpoints{job_name=~\"$job_name\"}[2m])",
     "legendFormat": "{{job_name}} FailedCheckpoints"
    }
   ]
  },
  {
   "title": "connector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "offset commit failures to Kafka",
   "type": "graph",
   "description": "offset commit failures to Kafka",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flink_taskmanager_job_task_operator_commitsFailed{job_name=~\"$job_name\"}[2m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "records has dropped due to arriving late.",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numLateRecordsDropped{job_name=~\"$job_name\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "job-downtime",
   "type": "graph",
   "description": "job-downtime",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_job_downtime{job_name=~\"$job_name\"}",
     "legendFormat": "{{job_name}}_downtime"
    }
   ]
  },
  {
   "title": "rocksdb",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "delayed write rate",
   "type": "graph",
   "description": "delayed write rate",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_counter_rocksdb_actual_delayed_write_rate{job_name=~\"$job_name\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": " entries in the unflushed immutable memtables",
   "type": "graph",
   "description": "entries in the unflushed immutable memtables.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_counter_rocksdb_num_deletes_imm_mem_tables{job_name=~\"$job_name\"}",
     "legendFormat": "{{task_name}} delete entries"
    },
    {
     "expr": "flink_taskmanager_job_task_operator_counter_rocksdb_num_entries_imm_mem_tables{job_name=~\"$job_name\"}",
     "legendFormat": "{{task_name}} total entries"
    }
   ]
  },
  {
   "title": "background errors in RocksDB",
   "type": "graph",
   "description": "background errors in RocksDB",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_counter_rocksdb_background_errors{job_name=~\"$job_name\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "unreleased snapshots",
   "type": "graph",
   "description": "unreleased snapshots",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_counter_rocksdb_num_snapshots{job_name=~\"$job_name\"}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JobManager Memory Available",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Max-flink_jobmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "{{instance}}可用堆内存"
    }
   ]
  },
  {
   "title": "TaskManager Memory Available",
   "type": "graph",
   "description": "TaskManager Memory Available",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Max-flink_taskmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "{{instance}}:{{tm_id}}可用堆内存"
    }
   ]
  },
  {
   "title": "JobManager NonHeap Memory Available",
   "type": "graph",
   "description": "JobManager NonHeap Memory Available",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Committed-flink_jobmanager_Status_JVM_Memory_NonHeap_Used",
     "legendFormat": "{{instance}}NoHeap可用内存"
    }
   ]
  },
  {
   "title": "TaskManger NonHeap Memory Available",
   "type": "graph",
   "description": "TaskManger NonHeap Memory Available",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Committed-flink_taskmanager_Status_JVM_Memory_NonHeap_Used",
     "legendFormat": "{{instance}}:{{tm_id}}NoHeap可用"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "jobmanager network  Rate per second",
   "type": "graph",
   "description": "jobmanager network Rate per second",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_System_Network_bond0_ReceiveRate",
     "legendFormat": "{{host}} ReceiveRate"
    },
    {
     "expr": "flink_jobmanager_System_Network_bond0_SendRate",
     "legendFormat": "{{host}} SendRate"
    }
   ]
  },
  {
   "title": "TaskManager network Rate per second",
   "type": "graph",
   "description": "TaskManager network Rate per second",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_System_Network_bond0_ReceiveRate",
     "legendFormat": "{{host}} ReceiveRate"
    },
    {
     "expr": "flink_taskmanager_System_Network_bond0_SendRate",
     "legendFormat": "{{host}}    SendRate"
    }
   ]
  },
  {
   "title": "JobManager System Memory Available",
   "type": "graph",
   "description": "JobManager  System Memory Available",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 54 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_System_Memory_Available",
     "legendFormat": "{{instance}}可用内存"
    }
   ]
  },
  {
   "title": "TaskManager System Memory Available",
   "type": "graph",
   "description": "TaskManager System Memory Available",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_System_Memory_Available",
     "legendFormat": "{{instance}}可用内存"
    }
   ]
  },
  {
   "title": "JobManager CPU USE",
   "type": "graph",
   "description": "JobManager CPU USE",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_System_CPU_Usage",
     "legendFormat": "{{instance}}已用内存"
    }
   ]
  },
  {
   "title": "TaskManager CPU USE",
   "type": "graph",
   "description": "TaskManager CPU USE",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_System_CPU_Usage",
     "legendFormat": "{{instance}}已用内存"
    }
   ]
  }
 ]
}